import argparse
import glob
import os
import tempfile
import shutil
from multiprocessing import Pool, cpu_count
from functools import partial
import logging

import polars as pl
from yirgacheffe.layers import RasterLayer  # type: ignore

from methods.matching.calculate_k import build_layer_collection
from methods.common.luc import luc_range

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(processName)s %(message)s")

def process_partial_raster(
    start_year: int,
    evaluation_year: int,
    matching_zone_filename: str,
    jrc_directory_path: str,
    fcc_directory_path: str,
    ecoregions_directory_path: str,
    elevation_directory_path: str,
    slope_directory_path: str,
    access_directory_path: str,
    countries_raster_filename: str,
    temp_output_dir: str,
    partial_raster_path: str
) -> str:
    """Processes one partial M raster and saves its table data to a temp parquet file."""
    logging.info(f"Processing partial raster: {partial_raster_path}")
    partial_raster_filename = os.path.basename(partial_raster_path)
    temp_parquet_filename = os.path.join(temp_output_dir, partial_raster_filename.replace('.tif', '.parquet'))

    try:
        partial_raster = RasterLayer.layer_from_file(partial_raster_path)

        matching_collection = build_layer_collection(
            partial_raster.pixel_scale,
            partial_raster.projection,
            list(luc_range(start_year, evaluation_year)),
            [start_year, start_year - 5, start_year - 10],
            matching_zone_filename,
            jrc_directory_path,
            fcc_directory_path,
            ecoregions_directory_path,
            elevation_directory_path,
            slope_directory_path,
            access_directory_path,
            countries_raster_filename,
        )

        results = []
        luc_columns = [f'luc_{year}' for year in luc_range(start_year, evaluation_year)]
        fcc_columns = ['fcc0_u', 'fcc0_d', 'fcc5_u', 'fcc5_d', 'fcc10_u', 'fcc10_d']
        columns = ['lat', 'lng', 'ecoregion', 'elevation', 'slope', 'access', 'country'] + luc_columns + fcc_columns

        window = partial_raster.window
        logging.debug(f"Processing window {window} for {partial_raster_filename}")

        for yoffset_local in range(window.ysize):
            yoffset_global = window.yoff + yoffset_local
            row_matches = partial_raster.read_array(0, yoffset_local, window.xsize, 1)
            if not row_matches.any():
                continue

            row_elevation = matching_collection.elevation.read_array(window.xoff, yoffset_global, window.xsize, 1)
            row_ecoregion = matching_collection.ecoregions.read_array(window.xoff, yoffset_global, window.xsize, 1)
            row_slope = matching_collection.slope.read_array(window.xoff, yoffset_global, window.xsize, 1)
            row_access = matching_collection.access.read_array(window.xoff, yoffset_global, window.xsize, 1)
            row_countries = matching_collection.countries.read_array(window.xoff, yoffset_global, window.xsize, 1)
            row_lucs = [x.read_array(window.xoff, yoffset_global, window.xsize, 1) for x in matching_collection.lucs]
            row_fccs = [x.read_array(window.xoff, yoffset_global, window.xsize, 1) for x in matching_collection.fccs]

            for xoffset_local in range(window.xsize):
                if row_matches[0, xoffset_local] > 0:
                    xoffset_global = window.xoff + xoffset_local
                    coord = matching_collection.boundary.latlng_for_pixel(xoffset_global, yoffset_global)

                    results.append([
                        coord[0], coord[1],
                        row_ecoregion[0, xoffset_local],
                        row_elevation[0, xoffset_local],
                        row_slope[0, xoffset_local],
                        row_access[0, xoffset_local],
                        row_countries[0, xoffset_local],
                    ] + [luc[0, xoffset_local] for luc in row_lucs] + [fcc[0, xoffset_local] for fcc in row_fccs])

        if results:
            output_df = pl.DataFrame(results, schema=columns)
            output_df.write_parquet(temp_parquet_filename)
            logging.info(f"Wrote {len(results)} points to {temp_parquet_filename}")
            return temp_parquet_filename
        else:
            logging.info(f"No matching points found in {partial_raster_path}. No temp file created.")
            return None

    except Exception as e:
        logging.error(f"Error processing {partial_raster_path}: {e}", exc_info=True)
        return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Finds all potential matches to K in matching zone, aka set M.")
    parser.add_argument(
        "--rasters_directory",
        type=str,
        required=True,
        dest="m_rasters_directory",
        help="Directory containing partial M rasters (*.tif) generated by find_potential_matches.py"
    )
    parser.add_argument(
        "--matching",
        type=str,
        required=True,
        dest="matching_zone_filename",
        help="Filename of GeoJSON file desribing area from which matching pixels may be selected."
    )
    parser.add_argument(
        "--start_year",
        type=int,
        required=True,
        dest="start_year",
        help="Year project started."
    )
    parser.add_argument(
        "--evaluation_year",
        type=int,
        required=True,
        dest="evaluation_year",
        help="Year of project evaluation"
    )
    parser.add_argument(
        "--jrc",
        type=str,
        required=True,
        dest="jrc_directory_path",
        help="Directory containing JRC AnnualChange GeoTIFF tiles for all years."
    )
    parser.add_argument(
        "--fcc",
        type=str,
        required=True,
        dest="fcc_directory_path",
        help="Directory containing Coarsened Proportional Coverage GeoTIFF tiles for all years."
    )
    parser.add_argument(
        "--ecoregions",
        type=str,
        required=True,
        dest="ecoregions_directory_path",
        help="Directory containing Ecoregions GeoTIFF tiles."
    )
    parser.add_argument(
        "--elevation",
        type=str,
        required=True,
        dest="elevation_directory_path",
        help="Directory containing SRTM elevation GeoTIFF tiles."
    )
    parser.add_argument(
        "--slope",
        type=str,
        required=True,
        dest="slope_directory_path",
        help="Directory containing slope GeoTIFF tiles."
    )
    parser.add_argument(
        "--access",
        type=str,
        required=True,
        dest="access_directory_path",
        help="Directory containing access to health care GeoTIFF tiles."
    )
    parser.add_argument(
        "--countries-raster",
        type=str,
        required=True,
        dest="countries_raster_filename",
        help="Raster of country IDs."
    )
    parser.add_argument(
        "--output",
        type=str,
        required=True,
        dest="output_filename",
        help="Destination parquet file for results."
    )
    parser.add_argument(
        "--j",
        type=int,
        required=False,
        default=round(cpu_count() / 4),
        dest="processes_count",
        help="Number of concurrent threads to use."
    )
    args = parser.parse_args()

    partial_raster_files = glob.glob(os.path.join(args.m_rasters_directory, "*.tif"))
    if not partial_raster_files:
        logging.error(f"No *.tif files found in {args.m_rasters_directory}")
        return

    logging.info(f"Found {len(partial_raster_files)} partial M rasters to process.")

    with tempfile.TemporaryDirectory() as tempdir:
        logging.info(f"Using temporary directory for intermediate parquets: {tempdir}")

        worker_func = partial(
            process_partial_raster,
            args.start_year,
            args.evaluation_year,
            args.matching_zone_filename,
            args.jrc_directory_path,
            args.fcc_directory_path,
            args.ecoregions_directory_path,
            args.elevation_directory_path,
            args.slope_directory_path,
            args.access_directory_path,
            args.countries_raster_filename,
            tempdir
        )

        num_processes = min(args.processes_count, len(partial_raster_files))
        logging.info(f"Starting parallel processing with {num_processes} workers...")
        with Pool(processes=num_processes) as pool:
            temp_parquet_files = pool.map(worker_func, partial_raster_files)

        valid_temp_files = [f for f in temp_parquet_files if f is not None and os.path.exists(f)]

        if valid_temp_files:
            logging.info(f"Concatenating {len(valid_temp_files)} intermediate parquet files...")
            combined_df = pl.scan_parquet(valid_temp_files).collect()

            logging.info(f"Writing final combined table with {len(combined_df)} rows to {args.output_filename}")
            combined_df.write_parquet(args.output_filename)
        else:
            logging.warning("No valid intermediate parquet files were generated. Output file will not be created.")

    logging.info("Processing complete.")

if __name__ == "__main__":
    main()
