INPUT_DIR="/maps/jh2589/projects"
OUTPUT_DIR="/scratch/jh2589/pipeout/test"
JRC_DIR="/scratch/jh2589/jrc_2024/acc"
FCC_DIR="/scratch/jh2589/jrc_2024/fcc"
ECOR_GEOJSON="/maps/4C/ecoregions/ecoregions.geojson"
ECOR_DIR="/maps/4C/ecoregions"
ELEV_DIR="/maps/4C/elevation"
SLOPE_DIR="/maps/4C/slopes"
ACCESS_DIR="/maps/4C/access"
COUNTRIES_RASTER="/maps/4C/osm_boundaries.geojson"
OTHER_PROJECTS_DIR="/maps/mwd24/tmf-data/projects"
GEDI_INFO_DIR="/maps/4C/gedi/granule/info"
GEDI_DATA_DIR="/maps/4C/gedi/granule"
SRTM_ZIP_DIR="/scratch/jh2589/pipeout/srtm/zip"
SRTM_TIF_DIR="/scratch/jh2589/pipeout/srtm/tif"
SCC_CSV="/scratch/jh2589/scc.csv"
MATCH_BUFFER=500